services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    env_file:
      - ./localstack.env
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - GATEWAY_LISTEN=0.0.0.0:4566
      - LOCALSTACK_HOST=${LOCALSTACK_HOST}
    volumes:
      - ./data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
