---
k3d_cluster_name: "homelab"
k3d_docker_network: "k3d-homelab-net"
k3d_docker_subnet: "172.30.0.0/16"
k3d_docker_host: "{{ ansible_facts['env'].get('DOCKER_HOST', '') }}"
k3d_path_env: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

k3d_api_port: "6550"
k3d_hostname: "{{ k3d_hostname }}"
k3d_api_host: "{{ k3d_hostname }}"
k3d_api_host_ip: "0.0.0.0"
force_recreate: false

# User LaunchAgent (runs on login)
k3d_launchagent_label: "{{ plist_name }}"
k3d_launchagent_dir: "{{ ansible_facts['env'].get('HOME', '') }}/Library/LaunchAgents"
k3d_plist_path: "{{ k3d_launchagent_dir }}/{{ k3d_launchagent_label }}.plist"

# k3d config
k3d_config_dir: "/etc/k3d"
k3d_config_path: "{{ k3d_config_dir }}/{{ k3d_cluster_name }}.yaml"
